//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КамиллаЗиятдинова320_Pet2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int ID_pet { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_vid { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> ID_human { get; set; }
        public string Description { get; set; }
    
        public virtual Human Human { get; set; }
        public virtual Vid Vid { get; set; }
    }
}
